export const extremeTruthCompany = [
    { gender: 'both', question: 'Sing a song' },
    { gender: 'male', question: 'Show 6 packs' },
    { gender: 'female', question: 'Dance like nobody is watching' },
    { gender: 'both', question: 'Tell a joke that makes everyone laugh' },
    { gender: 'male', question: 'Do 10 push-ups' },
    { gender: 'female', question: 'Impersonate your favorite celebrity' },
    { gender: 'both', question: 'Speak in an accent for the next two rounds' },
    { gender: 'male', question: 'Give a dramatic reading of a nursery rhyme' },
    { gender: 'female', question: 'Act out a famous movie scene' },
    { gender: 'both', question: 'Share your most embarrassing moment' },
    { gender: 'male', question: 'Do your best animal impression' },
    { gender: 'female', question: 'Recite a tongue twister without making a mistake' },
    { gender: 'both', question: 'Create a rap about the person to your right' },
    { gender: 'male', question: 'Do a one-minute stand-up comedy routine' },
    { gender: 'female', question: 'Tell a funny childhood story' },
    { gender: 'both', question: 'Pretend to be a news anchor reporting a silly story' },
    { gender: 'male', question: 'Do the moonwalk across the room' },
    { gender: 'female', question: 'Speak in rhymes for the next three turns' },
    { gender: 'both', question: 'Do your best impression of a famous politician' },
    { gender: 'male', question: 'Show your best dance move' },
    { gender: 'female', question: 'Share a guilty pleasure song and sing along' },
    { gender: 'both', question: 'Tell a fictional story about the person to your left' },
    { gender: 'male', question: 'Share the last picture you took on your phone' },
    { gender: 'female', question: 'Do a cartwheel (if space allows)' },
    { gender: 'both', question: 'Compose a funny poem on the spot' },
    { gender: 'male', question: 'Do an impression of a famous cartoon character' },
    { gender: 'female', question: 'Reenact a famous commercial' },
    { gender: 'both', question: 'Share your weirdest dream' },
    { gender: 'male', question: 'Do 20 jumping jacks' },
    { gender: 'female', question: 'Tell a secret youve never shared before' },
    { gender: 'both', question: 'Create a silly handshake with the person to your right' },
    { gender: 'male', question: 'Wear socks on your hands for the next three turns' },
    { gender: 'female', question: 'Pretend you are a runway model and strut your stuff' },
    { gender: 'both', question: 'Share your most unusual talent' },
    { gender: 'male', question: 'Do an interpretive dance to a random song' },
    { gender: 'female', question: 'Share your favorite pickup line' },
    { gender: 'both', question: 'Create a superhero persona and describe your powers' },
    { gender: 'male', question: 'Give a shout-out to your favorite fictional character' },
    { gender: 'female', question: 'Perform a magic trick with everyday objects' },
    { gender: 'both', question: 'Do your best celebrity impersonation' },
    { gender: 'male', question: 'Tell a funny story using only three words at a time' },
    { gender: 'female', question: 'Do a handstand against a wall' },
    { gender: 'both', question: 'Act out a scene from your favorite movie' },
    { gender: 'male', question: 'Speak in an opera voice for the next three turns' },
    { gender: 'female', question: 'Do your best impression of a famous singer' },
    { gender: 'both', question: 'Tell a joke in a language other than your native language' },
    { gender: 'male', question: 'Do 15 squats' },
    { gender: 'female', question: 'Recall a cringe-worthy moment from your past' },
    { gender: 'both', question: 'Pretend to be a news reporter covering a bizarre event' },
    { gender: 'male', question: 'Do a freestyle rap about the last person who spoke' },
    { gender: 'female', question: 'Speak in a foreign accent for the next two rounds' },
    { gender: 'both', question: 'Tell a funny story from your childhood' },
    { gender: 'male', question: 'Do your best impression of a famous athlete' },
    { gender: 'female', question: 'Recreate a famous movie quote with enthusiasm' },
    { gender: 'both', question: 'Share a weird fact about yourself' },
    { gender: 'male', question: 'Dance like nobodys watching for the next minute' },
    { gender: 'female', question: 'Tell a joke that involves a pun' },
    { gender: 'both', question: 'Create a new dance move and demonstrate it' },
    { gender: 'male', question: 'Share a funny anecdote from your week' },
    { gender: 'female', question: 'Do your best impression of a famous TV show character' },
    { gender: 'both', question: 'Compose a silly and catchy jingle on the spot' },
    { gender: 'male', question: 'Act like a different gender for the next two turns' },
    { gender: 'female', question: 'Recite the alphabet backward without any mistakes' },
    { gender: 'both', question: 'Do your best animal impression for the next three turns' },
    { gender: 'male', question: 'Tell a funny story using emojis only' },
    { gender: 'female', question: 'Reenact a famous scene from a romantic movie' },
    { gender: 'both', question: 'Share your most embarrassing moment from high school' },
    { gender: 'male', question: 'Do a breakdance move (if you can)' },
    { gender: 'female', question: 'Act out a scene from your favorite childhood cartoon' },
];